export const H2A_CLI_MCP_TOOL_NAMES = [
  "h2a_register_instance",
  "h2a_discover_instances",
  "h2a_open_negotiation",
  "h2a_offer",
  "h2a_counteroffer",
  "h2a_sign",
  "h2a_stabilize",
  "h2a_inbox",
  "h2a_append_journal",
  "h2a_escalate",
  "h2a_session_open",
  "h2a_session_close",
  "h2a_discover_sessions",
  "h2a_nhi_report",
  "h2a_nhi_inventory",
  "h2a_nhi_attest",
  "h2a_nhi_offboard",
  "h2a_nhi_export",
  "h2a_blockage_raise",
  "h2a_blockage_list",
  "h2a_blockage_resolve"
] as const;
