apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: h2a-mcp
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - netpol-mirror.yaml
images:
  - name: rg.fr-par.scw.cloud/h2a-mcp/h2a-cli
    newName: rg.fr-par.scw.cloud/h2a-mcp/h2a-cli
    newTag: latest
