apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: h2a-mcp
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
images:
  - name: ghcr.io/rhanka/h2a-cli
    newName: ghcr.io/rhanka/h2a-cli
    newTag: latest
